### ISSUE TITLE
Want to add the Wildcard Matching Code with Explanation wherever needed.

### ISSUE THREAD

**Issue by singhkunal01** [Adi8080/Hactoberfest2021#311]
Hey @Adi8080 please assign this to me so that i can add the code for Wildcard Matching with explanation wherever needed in C++.
Thank You

**Comment by Anu-Mushkan** [comment]
Wants to add the Wildcard Matching Code with Explanation.

**Comment by nansri108** [comment]
hello sir can you please assign to me this issue because i really want to work on this issue.
