### ISSUE TITLE
Kadane Algorithm in c++

### ISSUE THREAD

**Issue by Vidhanjain143** [Adi8080/Hactoberfest2021#314]

**Comment by Vidhanjain143** [comment]
assign this to me.

**Comment by nitesh-30** [comment]
assign this project to me .because i have a good knowledge in dsa  .as per my knowledge i will solve your problem eassly

**Comment by ojKunal** [comment]
Please assign this issue to me , I can solve this with less time and space complexity..

**Comment by priyanshuanand166** [comment]
Assign this to me as i am well versed in dsa and i am pretty confident to give a unique merge request.

**Comment by Deepak-the-learner** [comment]
Assign this to me.
I am pretty confident that I can solve this problem in less time complexity and space complexity.
I will try my level best to make the code understandable.

**Comment by Rohans-7** [comment]
Please assign this issue to me. It will be a good first submission of mine on github.
