### ISSUE TITLE
Make Readme better 

### ISSUE THREAD

**Issue by Adi8080** [Adi8080/Hactoberfest2021#6]

**Comment by IsaacArnold** [comment]
Hi there - can I please work on making the README better?

**Comment by Adi8080** [comment]
Sure

**Comment by IsaacArnold** [comment]
I noticed the issue has been closed? 

Cheers,

Isaac Arnold

**Comment by Adi8080** [comment]
I opened again, firstly  star This repo and then follow another account and contribute projects from there

**Comment by IsaacArnold** [comment]
Thank you. I will work on this tonight. 

Can you please update to the correct hacktoberfest label? Currently the one here is spelt wrong.

**Comment by Adi8080** [comment]
Ok do it

**Comment by IsaacArnold** [comment]
Thank you!

**Comment by Adi8080** [comment]
Checkout my [Aditya664](https://github.com/Aditya664) there are some projects on hactoberfest, also make contribution on those projects.

**Comment by Adi8080** [comment]
If I close this issue don't worry make pr I'll definitely mearge it.

**Comment by IsaacArnold** [comment]
Sure thing - I'll work on this tonight and submit a PR for you to merge. Cheers!
